"""add feedback table and performance indexes

Revision ID: 23bc101a20f7
Revises: 
Create Date: 2026-01-23 18:05:41.285397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23bc101a20f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_conversation_user_updated', 'conversations', ['user_id', 'updated_at'], unique=False)
    op.create_index('ix_message_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_conversation_created', table_name='messages')
    op.drop_index('ix_conversation_user_updated', table_name='conversations')
    # ### end Alembic commands ###
